### PR TITLE
migrate edge-mc to kubestellar

### PR DESCRIPTION
**Pull request by xrstf**
This PR converts the Prow config for `kcp-dev/edge-mc` to `kubestellar/kubestellar`.

### CODE REVIEW

**Comment by xrstf** [comment]
/hold

to be merged once the repo was migrated and the kcp-ci-bot was added.

**Comment by clubanderson** [comment]
@xrstf kcp-ci-bot was added to kubestellar-administrators group.  invitation is pending acceptance

**Comment by clubanderson** [comment]
@embik can you or @nikhita accept the kcp-ci-bot invite to the kubestellar-admins group in kubestellar/kubestellar?

**Comment by clubanderson** [comment]
kcp-ci-bot is now added to kubestellar-admins.  PR is ready to merge

**Review by embik — APPROVED** [review]

**Pull request merged**
