### PR TITLE
bump golang to 1.22.2

### PR DESCRIPTION
**Pull request by mjudeikis**

### CODE REVIEW

**Comment by embik** [comment]
Does it make sense to go to Go 1.22 with the old-ish k8s version we have in kcp?

**Comment by mjudeikis** [comment]
I think its enough now to be on 1.21 due to toolchain changes but yes, agreed.

**Review by embik — APPROVED** [review]
/approve

turns out we need 1.22 for Kubernetes 1.30, so approving this.

**Pull request merged**
